# Utiliza la imagen base de Node.js
FROM node:18.17.1

# Establece el directorio de trabajo en el contenedor
WORKDIR /app/django-front-react

# Copia los archivos de requerimientos al contenedor
COPY django-front-react/package.json /app/django-front-react/

RUN npm install serve -g

# Instala las dependencias del frontend
RUN npm install

# Copia el resto de los archivos al contenedor
COPY django-front-react/ /app/django-front-react/

RUN npm run build

# Expone el puerto en el que se ejecuta el frontend React con Vite
EXPOSE 5000

# ENV VITE_API_URL=http://localhost:5000
ENV VITE_API_URL=http://web.biotico.cl:5000

RUN npm run build

# Servir los archivos estáticos del build con el servidor web incorporado de Node.js
CMD ["npx", "serve", "-s", "dist"]