# Utiliza la imagen base de Python para Django
FROM python:3.10.10

# Establece el directorio de trabajo en el contenedor
WORKDIR /app/django_rest_framework

# Copia los archivos de requerimientos al contenedor
COPY django_rest_framework/requirements.txt /app/django_rest_framework/

# Instala las dependencias
RUN pip install --no-cache-dir -r /app/django_rest_framework/requirements.txt

# Copia el resto de los archivos al contenedor
COPY django_rest_framework/ /app/django_rest_framework/

# Expone el puerto en el que se ejecuta el backend Django
EXPOSE 5000

# Comando para iniciar el backend Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:5000"]